version: 2

registries:
  github-packages:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/faezeh-kianimoravej/flink-job-parent"
    username: "faezeh-kianimoravej"
    password: ${{secrets.GH_PACKAGES_READ_TOKEN}}

updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - "github-packages"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
