name: Tenant B Flink Job CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: faezeh-kianimoravej/flink-platform/.github/workflows/flink-job-ci-template.yml@main
    with:
      image_name: tenant-b-flink-job
      dockerfile_path: Dockerfile
      jar_path: target/*.jar
      java_version: "21"
      artifact_repository: github-packages
    secrets:
      GH_PACKAGES_READ_TOKEN: ${{ secrets.GH_PACKAGES_READ_TOKEN }}
